# Generated by Django 4.2.1 on 2023-07-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dni', models.CharField(max_length=10)),
                ('ruc', models.CharField(max_length=11)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('status', models.IntegerField(choices=[(1, 'activo'), (0, 'inactivo')], default=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
