# Generated by Django 4.2.1 on 2023-07-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='current_phase',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='work',
            name='total_phase',
            field=models.IntegerField(default=0),
        ),
    ]
