# Generated by Django 4.2.1 on 2023-07-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_alter_work_deadline_alter_work_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='payment',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='work',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
