# Generated by Django 4.2.1 on 2023-07-22 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
