# Generated by Django 4.2.1 on 2023-07-25 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
