# Generated by Django 4.2.1 on 2023-07-23 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sequence', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(1, 'activo'), (0, 'inactivo')], default=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'INACTIVO'), (1, 'PENDIENTE'), (2, 'INICIADO'), (3, 'TERMINADO')], default=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='phase.phase')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.work')),
            ],
        ),
    ]
