# Generated by Django 4.2.1 on 2023-07-25 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_alter_work_deadline_alter_work_delivery_date'),
        ('phase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workphase',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='work.work'),
        ),
    ]
